<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h1>Kordian</h1>
        <h4 style="margin-left: 2%;">Chór</h4>
		<p>Co powieǳieli gwarem, Bóg tylko zrozumie,<br>
Jak modlitwę rozbita<a href="#1"><sup>[1]</sup></a> w morza głuchym szumie. </p>
<p style="margin-left: 2.5%;"><em>
Sześciu żołnierzy przyprowaǳają<a href=#2"><sup>[2]</spu></a> bladego Kordiana. Stawią przed Carem.... Wielkim<br>
Książę przybiega z wściekłością</em></p>
        
		<h4 style="margin-left: 2%;">Wielki Książę</h4>
		<p  style="margin-left: 2%;">
		do Kordiana, pieniąc się</p>
<p>Ha! psie polski! przyszedłeś — czemuś taki blady?<br>
Przewiǳiałeś, co czeka? Kacie! roskolniku!…<br>
Ty nosisz szlify? precz! precz! precz! Rozciskam gady.<br>
Rzucę cię pod kopyta trójrzędnego szyku<br>
Albo tu zwalę w piasek… i moją ostrogą<br>
Napiszę «wor»<a href="#3"<sup>[3]</a> na czole. Car ciebie darował<br>
Zemście mojej… Car ciebie sam w grobie pochował!<br>
Z książęcej dłoni diabły wydobyć nie mogą<br>
		</p>
		<h4 style="margin-left: 2%;">Car</h4>
		<p  style="margin-left: 2%;">na stronie</p><p>
Myśli, że mię oszuka?
		</p>
		<a name="1">[1] modlitwę rozbita — modlitwę rozbitka.[przypis edytorski]</a><br>
		<a name="2">[2] sześciu żołnierzy przyprowaǳają — ǳiś popr.: sześciu żołnierzy przyprowaǳa.[przypis edytorski]</a><br>
		<a name="3">[3] wor (ros.) — złoǳiej. [przypis edytorski]</a><br>
    </body>
</html>